### ISSUE TITLE
Update idea

### ISSUE THREAD

**Issue by Vojtitko** [crimilo/Discord-Mirror#1]
![image](https://user-images.githubusercontent.com/85036497/200059369-a545ca8f-9b3c-46c5-aec3-dffe57a43d2a.png)
Hey, the bot is amazing, great job, i wanted to ask/propose a feature for it which would be really nice if you could have a try at implementing it.
Is to basically make a version where 
Channel #1 is mirrored into first Webhook 
Channel #2 is mirrored into second Webhook 
Channel #3 is mirrored into third Webhook 
because now it mirrors all the channels into all webhooks, which is useful but only in some cases. 

Ill be trying to come up with a solution my self, but i am very unexpierienced with these types of scripts. Also if there is any way to contact you for example on discord id like to shoot you a msg.

**Comment by crimilo** [comment]
The bot already has this feature, you simply have to configure it as follows:

```json
{
  "token": "INSERT YOUR TOKEN HERE",
  "mirrors": [
    {
      "channel_ids": [
        "CHANNEL ID 1"
      ],
      "webhooks_urls": [
        "WEBHOOK URL 1"
      ]
    },
    {
      "channel_ids": [
        "CHANNEL ID 2"
      ],
      "webhooks_urls": [
        "WEBHOOK URL 2"
      ]
    }
  ]
}
```

In the config, `mirrors:` is a list of "mappings", so you can have as many as you like.

For anything else, you can dm me on Discord: **crimilo#3123.**
