### ISSUE TITLE
How to mirror the message reply?

### ISSUE THREAD

**Issue by asongdon** [crimilo/Discord-Mirror#12]
Hi,

How can I mirror the message reply?

**Comment by crimilo** [comment]
Can you elaborate more?

What do you mean with message reply?

**Comment by asongdon** [comment]
I meant to say when a user replies to another message, it currently appears as a normal message.

Do you have any suggestions on how to make the reply appear as a reply when mirrored?

**Comment by crimilo** [comment]
It's not possible.

This is because the message is sent through a webhook, which is a separate entity from a user account, and webhooks do not have the ability to do that.
