### ISSUE TITLE
Replace roles

### ISSUE THREAD

**Issue by louanfontenele** [crimilo/Discord-Mirror#13]
How to replace roles in this new version?

**Comment by crimilo** [comment]
From README.md:
> To replace mentions and ensure a valid reference on the mirrored server, you can define a content replacement like this:
```json
"replacements": {
   "content": [
      {
         "replace": "ORIGINAL_ROLE_OR_USER_OR_CHANNEL_ID",
         "with": "REPLACED_ROLE_OR_USER_OR_CHANNEL_ID"
      }
   ]
}
```
You no longer need to specify the server ID.
