### ISSUE TITLE
not sure why im getting this i followed the install instructions

### ISSUE THREAD

**Issue by whzgudx** [crimilo/Discord-Mirror#15]
> start
> NODE_NO_WARNINGS=1 node dist/index.js

'NODE_NO_WARNINGS' is not recognized as an internal or external command,
operable program or batch file.
PS C:\Users\ds\Desktop\gitbash\Discord-Mirror>

**Comment by crimilo** [comment]
I forgot to support windows for `npm start`.
Re-clone the repo and follow the "How to use" steps, you should be able to run it now.

**Comment by whzgudx** [comment]
thank you its working!
