### ISSUE TITLE
nitro stickers break the bot

### ISSUE THREAD

**Issue by brownelvis** [crimilo/Discord-Mirror#18]
whenever i use a discord nitro sticker the bot crashes saying it cant mirror an empty message.  is there anyway to ignore nitro stickers? or would the discord account that is mirroring need nitro to be able to mirror?

**Comment by mufcalerts** [comment]
is there a way to modify the rpm start command so this run continuously on a service such as replit?

**Comment by crimilo** [comment]
> is there a way to modify the npm start command so this run continuously on a service such as replit?

I don't quite understand what you mean. If you want the bot to never stop after starting it with `npm run start`, you can purchase a VPS and host the bot on it.
