### ISSUE TITLE
[Suggestion]: Add more options to mirror

### ISSUE THREAD

**Issue by louanfontenele** [crimilo/Discord-Mirror#2]
1. Option to use webhook image and name instead of origin/source server image and name
![image](https://user-images.githubusercontent.com/2886066/217468836-b9ac6e38-0584-4e35-81c8-725f57bc4ae7.png)

2. Add support to clone files as well (you can also clone images and videos and other files in general)

And please, don't give up on the project, this project is incredible and much desired and wanted, my sincere thanks to you, thank you very much.

**Comment by crimilo** [comment]
I will implement the features you suggested soon.

**Comment by louanfontenele** [comment]
> I will implement the features you suggested soon.

Thank you so much. I'll create a video talking about your script. Thanks again

**Comment by crimilo** [comment]
Done.
Re-clone the repo, and start over again since i rewrote the entire bot and the config changed a bit.
