### ISSUE TITLE
Messages >2000 characters crash the mirror

### ISSUE THREAD

**Issue by brownelvis** [crimilo/Discord-Mirror#20]
Maybe truncate anything over 2000 characters, send it as an embed, or break into multiple webhooks?

![image](https://github.com/crimilo/Discord-Mirror/assets/68781576/47967385-a9ea-49a6-851b-4dd9e3f1a8eb)

**Comment by Ciscog33k** [comment]
100% on board with splitting into parted messages with some sort of injected "messageID part 1/3" header.  Especially in consideration that Nitro allows 4,000 char messages now.

Just allow a 0.5-1.0 second delay on send as to not have the Rx side queue post them out of order.
