### ISSUE TITLE
Invalid Webhook URL

### ISSUE THREAD

**Issue by fellj4934** [crimilo/Discord-Mirror#30]
New to actually coding/setting things up myself without a UI, but have used bots before with webhooks etc, I'm running npm start after following all the previous instructions and getting the error code:

if (!url || url.length <= 1) throw new Error ( 'WEBHOOK_URL_INVALID' )

Using windows powershell, node.js, and VS Code.

I've tried different webhooks, etc.. not sure what the issue is. Any help would be appreciated. Thanks !

**Comment by crimilo** [comment]
Hi, the issue is that you configured an invalid webhook URL. Check all your `webhookUrls:` sections and find where you left an empty line like this:

```yml
webhookUrls:
  - ""
```

And remove it or change it to a valid webhook URL, such as:

```yml
webhookUrls:
  - "https://discord.com/api/webhooks/1166402289215559700/R5Lx9Gt7cdrgMTSZEuVbJdduMhUgisPIT1T6j7aRFQvVC02aN6jr-0ko4jC17jCD1hLr"
```

If you reply here with your `config.yml`, I'll point out the error for you.

**Comment by fellj4934** [comment]
Thanks, I can send the config but I have a quick question, when I open the config folder it comes up with the template without any information filled in. I am typing it in through VS Code and then trying npm start, do I need to move it into the folder for it to work properly?
