### ISSUE TITLE
Published messages double send

### ISSUE THREAD

**Issue by belg1o** [crimilo/Discord-Mirror#31]
If a message is published after it is sent once, it is sent again to the channel even if there are no edits & other changes to the message.

**Comment by crimilo** [comment]
I don't understand the issue. Can you provide me the steps to reproduce it?

**Comment by belg1o** [comment]
> I don't understand the issue. Can you provide me the steps to reproduce it?

Sure. 

1. Create an announcement channel on Discord; or convert existing channel to announcement (server has to be in community mode)
2. Setup bot as normal
3. Send a messgae to the announcement channel
4. Bot will mirror the message
5. Publish the message
6. Bot will mirror the same message.

**Comment by YazzzMirror** [comment]
This is happening to me as well. Have edits and stuff turned off and sometimes the mirror will double or sometimes even triple post the mirrored messages. No clue how it is happening

**Comment by crimilo** [comment]
I will fix this in a few days.
