### ISSUE TITLE
Role Issue

### ISSUE THREAD

**Issue by Jake10233** [crimilo/Discord-Mirror#36]
You closed my issue but you didnt even help me with it at all?

**Comment by YazzzMirror** [comment]
> You closed my issue but you didnt even help me with it at all?

Roles work fine

**Comment by Jake10233** [comment]
They dont though. Hence why the ticket was opened.

**Comment by YazzzMirror** [comment]
> They dont though. Hence why the ticket was opened.

It does work fine. Also your last ticket you had multiple issues in the code and did not follow instructions and also acted like a bitch toward the dev so not sure why you think he would help you. Goodluck with getting any help when you act like that

**Comment by Jake10233** [comment]
Bro who even are you? Lmao. My code has no issues in it actually. Im not gonna post my actual webhook in a GitHub for people to be able to use. And I had typed out the Everywhere part in here it wasnt copied and pasted, So why dont you reread what I said the first time. Same reason you have to open a ticket about double messages.

**Comment by crimilo** [comment]
Yazzz is right, it does work fine. Stop opening issues.
