### ISSUE TITLE
Webhook URL invalid

### ISSUE THREAD

**Issue by louanfontenele** [crimilo/Discord-Mirror#37]
After today, the 15th, Discord had some maintenance, I don't know for sure, but now the bot doesn't start, the console message says that the Webhook is wrong, even though I copy using the Discord copy button

![image](https://github.com/crimilo/Discord-Mirror/assets/2886066/338cdffd-2fea-40bb-a162-d9aa46bec510)

Console error:
![image](https://github.com/crimilo/Discord-Mirror/assets/2886066/86d864c0-c6e5-47f2-bb9a-c041fea33af7)

**Comment by louanfontenele** [comment]
Fixed.

**Comment by andrewingram928** [comment]
Howd you fix it?

**Comment by louanfontenele** [comment]
> Howd you fix it?

check if the link is discordapp.com/api/...., change to discord.com/api/....
