### ISSUE TITLE
Mirror more than one channel

### ISSUE THREAD

**Issue by copalol** [crimilo/Discord-Mirror#4]
hi,

cant mirror more channels with diffrent webhooks.

like

"channel_ids": [
        "21323576011711","870592220515111"],

"webhooks_urls": [
        "https://discord.com/api/webhooks/1074912028176678963/yETv1MAP71_dKmXSVmkgXVmib_bGRf498IGJ03K8BHscym5JcHlJ-zht_G-x-TW5Hx-v","https://discord.com/api/webhooks/10749122214889337/9ta3NT16hvCbC3RCbSVa6joG3sDSr7xCPyZRU80TDkzjjUSNfW_GhJGcVPgzxdOFGcUx","https://discord.com/api/webhooks/107422236617/TbznZrgXfrx2HgUHLXrGPQzUAQZ9MeEwDaAa2dsGdd6pC3tR1tYQOavE-ithsPNrvNyf"]

**Comment by crimilo** [comment]
```json
"mirrors": [
    {
      "channel_ids": [
        "channel_id_example_1"
      ],
      "webhooks_urls": [
        "webhook_url_example_1"
      ]
    },
    {
      "channel_ids": [
        "channel_id_example_2"
      ],
      "webhooks_urls": [
        "webhook_url_example_2"
      ]
    }
  ]
  ```

**Comment by copalol** [comment]
thanks it works! but since today i have a new bug.
when something was mirrored all user changed to the last mirrored user

**Comment by crimilo** [comment]
> thanks it works! but since today i have a new bug.
> 
> when something was mirrored all user changed to the last mirrored user

Can you provide more info?
How would i replicate the bug exactly?
Are you using the latest version with the latest config.json?

**Comment by copalol** [comment]
yeah updated version. first when i mirror.. i didnt get any notifications on phone ( ios )
when i close it works normal.

lets see here is an example


orginal chat : 

crimilo: hi
copa : hello
user 1 : peace

and this is on mirror 👍 

crimilo: hi
...
copa: hi
copa : hello
...
user 1: hi
user 1 : hello
user 1 : peace

**Comment by crimilo** [comment]
When the bot is mirroring, you won't get IOS notifications since for discord your client is online and the notifications are sent only when you are not online.

Still can't understand what is the bug, please provide me a step by step guide on how to replicate it and i will fix it.
