### ISSUE TITLE
URL Not valid

### ISSUE THREAD

**Issue by andrewingram928** [crimilo/Discord-Mirror#40]
Hey there, I read previous issues regarding URL's not being valid. I took your example config file setup, that was very trimmed down and basic, to make sure I wasn't somehow missing a field entry.

I had some issues getting my token, but I did end up finding it via a different method. I copy pasted my webhook URL, and Channel ID.

I keep trying different things and it just isnt working. Is there a chance my token isn't correct, would that throw this error?

BTW Im running CMD from the folder itself, pretty rookie coder, that couldnt cause any issues right? Had a problem navigating directory from within Node itself.

Let me know, thank you.

**Comment by louanfontenele** [comment]
remove the APP from the url 
ex: `https://discordAPP.com/api/webhooks/ID/ETC` to `https://discord.com/api/webhooks/ID/ETC`

**Comment by andrewingram928** [comment]
ty!
