### ISSUE TITLE
useWebhookProfile: true Not Working

### ISSUE THREAD

**Issue by TIAexe** [crimilo/Discord-Mirror#45]
![image_197](https://github.com/crimilo/Discord-Mirror/assets/84967975/03f97446-1a04-4eb8-90e8-14df7f1dc822)

Looks like it is not working properly since it should be sent with Discord User profile pic and Discord User name.

**Comment by crimilo** [comment]
it is using the webhook profile picture and name. just change it or set the option to false if you want to use the actual person discord profile.
