### ISSUE TITLE
Probleme using multi mirroir

### ISSUE THREAD

**Issue by Amiinnetdz** [crimilo/Discord-Mirror#46]
how to use multi forward Mirroir is not working for me
Mirrors:
1:
       channelIds:
       - "1144033077379743964"
       webhookUrls:
       - "https://discord.com/api/webhooks/****/YgUNpf0WvNc-kds8pKZM6AVqARHH2-s>

# Johny main
Mirrors3:

       channelIds:
       - "1144035250322800680"
       webhookUrls:
       - "https://discord.com/api/webhooks/*****/NWWfkiTw3p7P8PPnt4QJOxtRUfJn9zV>
# Chanllenge 1k spot
Mirrors4:
       channelIds:
       - "1144049936049119332"
       webhookUrls:
       - "https://discord.com/api/webhooks/*****/xU3qdz3kIMwB6KyintyUByfTGAaIqgA>

**Comment by whzgudx** [comment]
> Fixed using https://codebeautify.org/yaml-editor-online thank you it work

wait how did you do it i thought i had it figured out

**Comment by Amiinnetdz** [comment]
telegram @Amiinnetdz
