### ISSUE TITLE
Color change

### ISSUE THREAD

**Issue by Pali010** [crimilo/Discord-Mirror#55]
I can't change the color of embeds
![image](https://github.com/crimilo/Discord-Mirror/assets/83973658/2410b59f-2300-4e24-ac9c-67a44183670b)

**Comment by crimilo** [comment]
probably because the embed you're trying to replace isn't white (#ffffff).

to get the color of an embed you can take a screenshot of it and check the color using a graphics editor like photoshop or gimp.

alternatively, you can open discord in your browser to see the css and copy the color.

**Comment by crimilo** [comment]
if you want to replace any color with `#41E995`, you can use the wildcard `*` like this:
`replace: "*"`

**Comment by Pali010** [comment]
I tried everything, if I put the wild card it show me that I need to put a valid hex color. Also I tried to send and embed white (#ffffff) and replace with a random hex red and it send always white embed

**Comment by crimilo** [comment]
you have configured the wrong color then.

in any case i updated the bot so that you can also use the wildcard for embed colors.

pull the latest version ;)
