### ISSUE TITLE
whitelist with keyword inside embed posted by bot isn't mirroring

### ISSUE THREAD

**Issue by Endracion** [crimilo/Discord-Mirror#57]
Hello, I'm not sure if it's such a unique combination that it just doesn't work, but I've set the mirror to pick up what a bot posts which is always an embed.

Without the filter, the mirror works fine, so I know the rest of the settings are ok, but of course it just mirrors everything. Once I set the filter to whitelist + keyword, nothing gets mirrored anymore. Is it because it doesn't look inside the embed for keywords to filter, or something else possibly?

I have made it successfully replace some words from the embed using the replace function, so I was assuming it can read inside of the embed already.

EDIT: Just to be clear, I have also been able to replace the same keyword from the filter with the replace function, it's really just the filter function that it's not working for.

**Comment by crimilo** [comment]
the filter does "look inside" the embed. it checks the message content and the following embed properties:
- title
- description
- field name and value
- footer text
- author name

if it isn't mirroring its probably because the message did not contain any whitelisted words or the bot is not configured correctly.

please send your config there with screenshots of the message not being mirrored.

**Comment by Endracion** [comment]
The bot I'm mirroring posts a list of static titles with changing information (such as event, sport, name), but all the tiles are fixed, and I used said titles to test the filtering as it should have continued to mirror everything, yet it stopped completely when it was turned on to whitelist.

Here's the relevant part, there's really not much to it; I even tried post_type, not that I knew what that does.

`      # Filter allows you to only mirror messages that contain or do not contain specific keywords.
      filter:
         # "whitelist": only mirror messages that contain at least one of the keywords.
         # "blacklist": only mirror messages that do not contain any of the keywords.
         # "none": do not filter messages.
         **type: "whitelist"**
         keywords:
            **- "Event"**
         # The where option is used to specify where the filter should be applied.
         # The available options are: message, post_tag.
         **where: "message"`**

**Comment by crimilo** [comment]
that should work, try to recreate the message with https://discohook.org/ and see if it gets mirrored

**Comment by Endracion** [comment]
I have recreated it in discohook, which I'm familiar with as I've used it before, and it indeed does not trigger when whitelisted there either.

It's the same behavior as I described. Try it for yourself: https://share.discohook.app/go/3dxa3yuq

**Comment by crimilo** [comment]
i fixed the bug. pull the latest version and recompile the bot with `npm run compile`.

thank you for the report ;)

**Comment by Endracion** [comment]
Awesome! Thanks for the fix.

I've tested it and it works as expected.
