### ISSUE TITLE
Webhook profiles

### ISSUE THREAD

**Issue by dede5859** [crimilo/Discord-Mirror#6]
Does webhook profiles need to be false? And its not allowed to be online that user in the token which list in json?

**Comment by crimilo** [comment]
> Does webhook profiles need to be false?

Depends on your needs, if you set `use_webhook_profile:` to `true` in config.json, you will use the profile of the webhook where the mirrored message is sent, for example:
![2023-02-19_14-28](https://user-images.githubusercontent.com/111324740/219951252-73f01b96-74df-4d4d-8cc3-f1e2c567a543.png)
Instead, if you set `use_webhook_profile:` to `false`, the profile of the mirrored message is going to be the profile of the original message author, for example:
Original message: ![original message](https://camo.githubusercontent.com/72767a6bb2eba3cb4489fa60630b77161aae4d8072f9358d0185b62da376ccf3/68747470733a2f2f692e696d6775722e636f6d2f6f67656c4a32332e706e67)
Mirrored message: ![mirrored message](https://camo.githubusercontent.com/383640957c7ff668033e6efbac9d1561c5cea0dfa005c61eaad500a23bd05a92/68747470733a2f2f692e696d6775722e636f6d2f4334324f5436342e706e67)

> And its not allowed to be online that user in the token which list in json?

You mean: can i be online with my account when the bot starts?
If so, yes, you can be online when the bot starts, that's fine, but the account status won't change to the configured one.
