### ISSUE TITLE
Suggestion for a specific use case

### ISSUE THREAD

**Issue by strotski** [crimilo/Discord-Mirror#62]
HI,

I need an option that will anonymize the people/avatars but display the server/channel it's pulling from because in my particular use case I am pulling from a lot of servers and a lot of channels all into one channel on my server.

Example:
Server 1 channel 1 msg
<anonymized message>
Server 2 channel 1 msg
<anonymized message>
Server 1 channel 2 msg
<anonymized message>

etc

Reason being is me needing to keep an eye on things but also being able to distinguish where the messages are coming from.
Is that possible to do?

**Comment by crimilo** [comment]
to display the source guild and channel i would have to add them to the mirrored message or send a new message after each mirror specifying them.

this isn't a feature i intend to add, sorry.

however, the bot is open source, so you can fork it and add it yourself. :)
