### ISSUE TITLE
(node:5620) DeprecationWarning: Intents is not available. (Use node --trace-deprecation ... to show where the warning was created)

### ISSUE THREAD

**Issue by wirdo89** [crimilo/Discord-Mirror#69]
Hey there,

First of all, thanks for all your work.
Yesterday I restarted the mirror and an error came up. I checked but the depedencies are still the same version (also tried with the newest discord selfbot)

(node:5620) DeprecationWarning: Intents is not available.
(Use node --trace-deprecation ... to show where the warning was created)

Any advise on this?

edit:
When removing this line from index.js
intents: [discord_js_selfbot_v13_1.Intents.FLAGS.GUILD_MESSAGES, discord_js_selfbot_v13_1.Intents.FLAGS.MESSAGE_CONTENT]

The mirror works again but renaming the author of the original embed (and perhaps some other things) don't work anymore.

**Comment by jZeko** [comment]
Mind helping me set it up? Still struggling to get the bot working
