### ISSUE TITLE
'WEBHOOK_URL_INVALID'

### ISSUE THREAD

**Issue by BROCHIBRO** [crimilo/Discord-Mirror#75]
# Webhooks are used to send mirrored messages to specific channels.                                 #
      # You can create a webhook for a channel with:                                                      #
      # Edit channel -> Integrations -> Webhooks -> New webook.                                           #
      webhookUrls:                                                                                        #
         - "https://discord.com/api/webhooks/1259496957551054930/xhQHE46gDZQNQwBKRXZWahxmnBQuxSR0KQoUNwa-CdXEthjV6V-7LsuQqu54BB7QuZ14" 

I cant fix it!!

**Comment by alvin-leong** [comment]
How did you resolve this?

**Comment by alvin-leong** [comment]
I had this error too, figured it out, don't leave any placeholder mirror in the config.yaml basically.
