### ISSUE TITLE
Channel replacement.

### ISSUE THREAD

**Issue by CryptoSalade** [crimilo/Discord-Mirror#79]
If i have a channel whos linked like this:
![daily](https://github.com/user-attachments/assets/bc2beb99-bb77-402f-b71c-7f15c0cd07dd)
What do i have to do in replacement?
Replace the url?  

      replacements:                                                                              
         1:                                                                                       
            replace: "https://discord.com/channels/XXXXXX"                                                                  
            with: "https://discord.com/channels/YYYYYY"                                                                        
            where: "embed_url"

**Comment by crimilo** [comment]
no, you have to replace the id of the #daily channel.

right click on the #daily channel -> copy id

then paste the id like this:

replace: "paste_id_here"
