### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by haroonjamil** [crimilo/Discord-Mirror#8]
Option to choose "embedonly: yes/no" for webhooks configured in config.json
Also, what's ur discord tag? Have a job for you :)

**Comment by crimilo** [comment]
you mean an option to only mirror messages that contain exclusively embeds?

**Comment by haroonjamil** [comment]
yes, correct.

**Comment by crimilo** [comment]
next update

**Comment by haroonjamil** [comment]
How can i contact you privately?

**Comment by crimilo** [comment]
crimilo#3123

**Comment by crimilo** [comment]
i implemented your suggestion in this update.
please clone the repo again, i fixed a bug in the commit i just released.
